"""
Grid HTML Renderer

Renders Grid objects as interactive HTML visualizations showing
component placements at each stage of the pipeline.
"""

from typing import List, Tuple
from src.pipeline.data_models import Grid, ComponentType
from datetime import datetime


class GridHTMLRenderer:
    """Renders grids as HTML with color-coded components."""

    # Color scheme for different component types
    COLORS = {
        ComponentType.LIGHT: "#FFD700",          # Gold
        ComponentType.AIR_SUPPLY: "#87CEEB",     # Sky Blue
        ComponentType.SMOKE_DETECTOR: "#FF6B6B", # Red
    }

    def render_pipeline_stages(
        self,
        stages: List[Tuple[str, Grid]],
        output_path: str
    ) -> str:
        """
        Render multiple pipeline stages side-by-side.

        Args:
            stages: List of (stage_name, grid) tuples
            output_path: Where to save the HTML file

        Returns:
            Path to the generated HTML file
        """
        html = self._generate_html(stages)

        with open(output_path, 'w') as f:
            f.write(html)

        return output_path

    def _generate_html(self, stages: List[Tuple[str, Grid]]) -> str:
        """Generate complete HTML document."""

        stages_html = "\n".join([
            self._render_stage(name, grid, idx)
            for idx, (name, grid) in enumerate(stages)
        ])

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ceiling Grid Pipeline Visualization</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🏗️ Ceiling Grid ML Pipeline Results</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>

        <div class="legend">
            <h3>Component Types</h3>
            <div class="legend-items">
                <div class="legend-item">
                    <div class="legend-color" style="background-color: {self.COLORS[ComponentType.LIGHT]}"></div>
                    <span>Light</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background-color: {self.COLORS[ComponentType.AIR_SUPPLY]}"></div>
                    <span>Air Supply</span>
                </div>
                <div class="legend-item">
                    <div class="legend-color" style="background-color: {self.COLORS[ComponentType.SMOKE_DETECTOR]}"></div>
                    <span>Smoke Detector</span>
                </div>
            </div>
        </div>

        <div class="stages-container">
            {stages_html}
        </div>

        <footer>
            <p>Generated by Ceiling Grid ML Pipeline | Apache Airflow</p>
        </footer>
    </div>

    <script>
        {self._get_javascript()}
    </script>
</body>
</html>"""

    def _render_stage(self, stage_name: str, grid: Grid, stage_idx: int) -> str:
        """Render a single pipeline stage."""

        # Count components by type
        counts = grid.count_components()
        light_count = counts.get(ComponentType.LIGHT, 0)
        air_count = counts.get(ComponentType.AIR_SUPPLY, 0)
        smoke_count = counts.get(ComponentType.SMOKE_DETECTOR, 0)
        total_count = len(grid.cells)

        # Generate grid cells
        grid_cells = self._render_grid_cells(grid)

        return f"""
        <div class="stage" data-stage="{stage_idx}">
            <div class="stage-header">
                <h2>Stage {stage_idx + 1}: {stage_name}</h2>
                <div class="stage-stats">
                    <div class="stat">
                        <span class="stat-label">Total Components:</span>
                        <span class="stat-value">{total_count}</span>
                    </div>
                    <div class="stat">
                        <span class="stat-label">Lights:</span>
                        <span class="stat-value" style="color: {self.COLORS[ComponentType.LIGHT]}">{light_count}</span>
                    </div>
                    <div class="stat">
                        <span class="stat-label">Air Supply:</span>
                        <span class="stat-value" style="color: {self.COLORS[ComponentType.AIR_SUPPLY]}">{air_count}</span>
                    </div>
                    <div class="stat">
                        <span class="stat-label">Smoke Detectors:</span>
                        <span class="stat-value" style="color: {self.COLORS[ComponentType.SMOKE_DETECTOR]}">{smoke_count}</span>
                    </div>
                </div>
            </div>
            <div class="grid" style="grid-template-columns: repeat({grid.width}, 1fr); grid-template-rows: repeat({grid.height}, 1fr);">
                {grid_cells}
            </div>
        </div>
        """

    def _render_grid_cells(self, grid: Grid) -> str:
        """Render all grid cells with components."""

        # Create a map of (x, y) -> cell for quick lookup
        cell_map = {(cell.x, cell.y): cell for cell in grid.cells}

        # Generate HTML for each cell
        cells_html = []
        for y in range(grid.height):
            for x in range(grid.width):
                cell = cell_map.get((x, y))
                cell_html = self._render_cell(x, y, cell)
                cells_html.append(cell_html)

        return "\n".join(cells_html)

    def _render_cell(self, x: int, y: int, cell) -> str:
        """Render a single grid cell."""

        if not cell or cell.component == ComponentType.EMPTY:
            # Empty cell
            return f"""
                <div class="cell empty" data-x="{x}" data-y="{y}">
                    <span class="cell-coords">{x},{y}</span>
                </div>
            """

        # Cell with component
        color = self.COLORS.get(cell.component, "#CCCCCC")
        type_icon = self._get_component_icon(cell.component)

        return f"""
            <div class="cell filled" data-x="{x}" data-y="{y}" style="background-color: {color};">
                <span class="component-icon">{type_icon}</span>
                <span class="cell-coords">{x},{y}</span>
                <div class="tooltip">
                    <strong>{cell.component.value}</strong><br>
                    Position: ({x}, {y})
                </div>
            </div>
        """

    def _get_component_icon(self, component_type: ComponentType) -> str:
        """Get emoji icon for component type."""
        icons = {
            ComponentType.LIGHT: "💡",
            ComponentType.AIR_SUPPLY: "🌬️",
            ComponentType.SMOKE_DETECTOR: "🚨",
        }
        return icons.get(component_type, "❓")

    def _get_css(self) -> str:
        """Generate CSS styles."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            padding: 40px;
        }

        header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #667eea;
            padding-bottom: 20px;
        }

        h1 {
            font-size: 2.5em;
            color: #333;
            margin-bottom: 10px;
        }

        .timestamp {
            color: #666;
            font-size: 0.9em;
        }

        .legend {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }

        .legend h3 {
            color: #333;
            margin-bottom: 15px;
        }

        .legend-items {
            display: flex;
            gap: 30px;
            flex-wrap: wrap;
        }

        .legend-item {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .legend-color {
            width: 30px;
            height: 30px;
            border-radius: 4px;
            border: 2px solid #333;
        }

        .stages-container {
            display: flex;
            flex-direction: column;
            gap: 40px;
        }

        .stage {
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            padding: 20px;
            background: #fafafa;
        }

        .stage-header {
            margin-bottom: 20px;
        }

        .stage-header h2 {
            color: #667eea;
            margin-bottom: 15px;
        }

        .stage-stats {
            display: flex;
            gap: 20px;
            flex-wrap: wrap;
        }

        .stat {
            background: white;
            padding: 10px 15px;
            border-radius: 6px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .stat-label {
            color: #666;
            font-size: 0.9em;
            margin-right: 5px;
        }

        .stat-value {
            font-weight: bold;
            font-size: 1.1em;
        }

        .grid {
            display: grid;
            gap: 2px;
            background: #ccc;
            padding: 2px;
            border-radius: 4px;
            max-width: 100%;
            aspect-ratio: 1;
        }

        .cell {
            background: white;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            position: relative;
            cursor: pointer;
            transition: all 0.2s;
            min-height: 40px;
        }

        .cell.empty {
            background: #f5f5f5;
        }

        .cell.filled {
            border: 2px solid rgba(0, 0, 0, 0.2);
        }

        .cell:hover {
            transform: scale(1.05);
            z-index: 10;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .component-icon {
            font-size: 1.5em;
        }

        .cell-coords {
            font-size: 0.7em;
            color: #666;
            margin-top: 2px;
        }

        .cell.empty .cell-coords {
            color: #ccc;
        }

        .tooltip {
            display: none;
            position: absolute;
            bottom: 100%;
            left: 50%;
            transform: translateX(-50%);
            background: rgba(0, 0, 0, 0.9);
            color: white;
            padding: 8px 12px;
            border-radius: 4px;
            white-space: nowrap;
            font-size: 0.85em;
            z-index: 100;
            margin-bottom: 5px;
        }

        .cell:hover .tooltip {
            display: block;
        }

        footer {
            margin-top: 40px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
        }

        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }

            h1 {
                font-size: 1.8em;
            }

            .stages-container {
                gap: 20px;
            }
        }
        """

    def _get_javascript(self) -> str:
        """Generate JavaScript for interactivity."""
        return """
        // Add smooth scrolling
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                document.querySelector(this.getAttribute('href')).scrollIntoView({
                    behavior: 'smooth'
                });
            });
        });

        // Log component clicks
        document.querySelectorAll('.cell.filled').forEach(cell => {
            cell.addEventListener('click', function() {
                const x = this.getAttribute('data-x');
                const y = this.getAttribute('data-y');
                console.log(`Clicked component at (${x}, ${y})`);
            });
        });
        """
